server:
    port: 8080

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/GuidoComp/TurismoApp-Microservicios.git
          searchPaths: config-data
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}